### ISSUE TITLE
Renaming LifeCycle implementation methods 'onCreate' and 'onDestroy'.

### ISSUE THREAD

**Issue by Joepeman** [cookingfox/chefling-di-java#1]
Hello Abel,

I understand the choice of using names 'onCreate' and 'onDestroy' for the LifeCycle implementation methods from an Android perspective, however working with pure Java in an embedded programming context I'm not sure wether the methods should be called 'onCreate' and 'onDestroy'.

Within the context of Chefling 'onCreate' is called whenever Chefling considers something is created, and 'onDestroy' when Chefling decides an Object has come to its final destination. In both 'onCreate' as 'onDestroy' I expect a 'LifeCycle' to provide the main 'hooks' for the beginning and ending of certain parts of my application. 

Having said that, I would expect LifeCycle to be a fitting hook for my main application lifecycle and therefore provide fitting methods, such as "setup" and "dispose". Let me try to explain from my perspective within an application:

Current names:
- onCreate: tells that something is actually created, which would suggest it exists. In an abstract way it tells you that 'Hey, I'm created, now you can do whatever you like'. However, it does not say anything about what is created.
- onDestroy: indicates something is destroyed? Looking at onCreate this could mean that the object is either being destroyed, or is going to be destroyed..?

Versus:
- setup: a commonly used method name indicating you have reached the setup part of the application or Object, do here whatever is necessary to prepare and initialize whatever you need to do. At this moment you decide what should start to exist and what not.
- dispose: telling you that 'Hey, the application or this part of the application is going to end! Do whatever you need to do, maybe garbage collect?'. It does NOT tell you 'something' is or is going to be destroyed.

What makes setup and dispose so interesting in a life cycle is that both methods are only executed once. I somewhat understand the use of onCreate and onDestroy within an Android perspective (creating and destroying activities, fragments etc.), but working with Chefling and a Lifecycle implementation I really do believe 'setup' and 'dispose' is a cleaner, clearer and more global approach. Let me know what you think! Sorry for the big post, I'll pass you a potato.

Thanks,
Joep

**Comment by abelcookingfox** [comment]
Hi Joep,

Thanks for the comment!

I agree that the LifeCycle method naming has its problems. It is not immediately clear at what stage the lifecycle is when those methods are called. Yes, I was inspired by Android when naming those methods like they are now, and what I liked most about the naming was how the "on" prefix indicates that is a lifecycle _event_. However, for `onCreate` it would probably have been better if it was named `onCreated`, indicating that the Container created an instance of the class. Event names are clearer when using past tense anyway. Unfortunately the same can not be applied to the other method, since `onDestroyed` is just not accurate: the instance will only be destroyed AFTER this method is called.

So I am all for finding a better alternative. I think it is important to use names that are familiar to Java developers (since this is a Java library) and general enough for any developer to understand. So I started thinking about your suggestions and possible alternatives, also investigating the naming conventions of other dependency injection frameworks, and came up with the following:

`onCreate`:
- **create**: I think is okay, although it suggests 'constructor' too much.
- **setup**: I almost never see this in a Java context to be honest.
- **init**: used often, but I'd rather not use an abbreviation.
- **initialize**: I like a lot, very common and it clearly describes the lifecycle phase we are in.
- **start**: used more often that I expected, but I don't like it for this purpose really, since it suggests there might also be something like pause, resume, etc.
- **construct**: name of the [PHP5 constructor](http://php.net/manual/en/language.oop5.decon.php), so for me it suggests 'constructor' too much.

`onDestroy`:
- **destroy**: used quite often and in my opinion clearly describes the goal of the method.
- **dispose**: see "destroy".
- **terminate**: I like as well, although it 'feels' more like a situation that only occurs when the application exits.
- **finalize**: not an option, since it's a [default Java method](http://stackoverflow.com/questions/2506488/when-is-the-finalize-method-called-in-java).
- **stop**: see "start".
- **destruct**: see "construct".
- **release**: pretty decent, but a bit vague.
- **close**: okay, but I don't think the opposite, "open", is an option.

I read [a discussion](http://programmers.stackexchange.com/questions/163004/what-is-the-opposite-of-initialize-or-init) about this subject and they came up with similar names. I also thought of other options (free, end, done...) but didn't like them.

There is a Java Specification Request ([JSR 250](https://en.wikipedia.org/wiki/JSR_250)) that contains annotations for the specific situation we're talking about and they use `@PostConstruct` and `@PreDestroy`. There are several DI frameworks that have implemented this specification. Although these names describe the lifecycle phase very accurately, I think `postConstruct()` and `preDestroy()` are not the best method names. Good method names are verbs.

These are the terms used by other Java DI frameworks that I investigated:
- [Java EE6 CDI](http://docs.oracle.com/javaee/6/tutorial/doc/gmgkd.html): PostConstruct & PreDestroy (annotations)
- [HK2](https://hk2.java.net/2.4.0-b31/api-overview.html#Unmanaged_Creation_Injection_and_Lifecycle): postConstruct & preDestroy
- [Spring](http://javabeginnerstutorial.com/spring-framework-tutorial/java-spring-bean-lifecycle/): init & destroy
- [PicoContainer](http://picocontainer.com/lifecycle.html): start & dispose
- [GuiceBox](https://code.google.com/p/guicebox/wiki/GuiceBox): Start & Kill (annotations)

Currently, I think I like "initialize" and "dispose" most of all of these options.

I'm curious if your opinion has changed after these thoughts. :)

Abel

PS: I like potato!

**Comment by Joepeman** [comment]
Hi Abel,

Thank you for the elaborated answer.

I do agree with you on the diversity of conventions used by other programming languages. I like "initialize" and "dispose" for they're short and strong expressions leaving enough freedom to the developer about what he wants to do after one of the methods is called.

While reading your answer I realized once "initialize" is used, you won't be able to use it in another context, and you really shouldn't. The idea of "initialize", just as "setup", is that they only run once during application startup and shutdown. Using the LifeCycle implementation means you need to adopt the flow of "initialize" and "dispose", being cautious of using the two words in other places within your code that is NOT a LifeCycle implementation.

I hope my answer is clear, here's the potato:  0  :)

Joep

**Comment by abelcookingfox** [comment]
Hey Joep,

Just a small comment - you say:

> Using the LifeCycle implementation means you need to adopt the flow of "initialize" and "dispose", being cautious of using the two words in other places within your code that is NOT a LifeCycle implementation.

You are definitely right about being cautious, so I wanted to mention the following: the interesting part about your remark is that when you use `initialize` and `dispose` (or something similar) in a class that does not implement LifeCycle, maybe you SHOULD implement the interface! The benefit is that Chefling will **automatically** call those methods when an instance of the class is created and destroyed. This makes your code more maintainable, since you won't (for example) have to chain multiple initialize methods within child classes.

:)

Abel

**Comment by cookingfox** [comment]
LifeCycle method naming was changed in version 4:
- `onCreate()` -> `initialize()`
- `onDestroy()` -> `dispose()`
